# TODO: Apply ChrX QC filters to CNV calls - Remove dodgy calls
# 
# Author: pv1
###############################################################################

# Input CNV calls data frame with the following columns (with 'column names' in brackets):
# - CoNVex score (convex_score)
# - Mean log2 ratio (mean_l2r)
# - MAD of log2 ratio
# - Internal frequency proportion at 50% reciprocal overlap (rc50_internal_freq)
# - common_forward and common_backward overlap proportion (output of recipeB package OR CoNVex's ChrOverlap() function)
# - RETURNS CHRX CALLS AFTER QC
# QC CHECK FOR:
#  CASE 1 - >10Mb ChrX calls in any sample (remove all ChrX calls in those samples)
#  CASE 2 - >1Mb calls in outlier (medianX vs. medianAuto)  samples
#  CASE 3 - All calls in gender 'U' (unknown) samples - remove all ChrX calls 
#  - Apply all other Autosomal filtering criteria in ADDITION - call CallQC() function from here
# REMOVAL CRITERIA:
#  - Remove CNVs of samples matching Case 1 & Case 3
#  - Remove CNVs of samples matching Case 2 (both 2a and 2b)
# Possible extension: Mark Case 2a samples' ChrX as only match as 'FAIL' ??

`CallQCChrX` <- function(cnv_calls = data.frame(), sample_meansmads = data.frame(), sd_medians = 2, abs_medianX_cutoff = 0.5, outlier_plot_file="") {
	
	cnv_calls_names = c("convex_score","mean_l2r","mad_l2r","rc50_internal_freq","common_forward","common_backward");
	present = cnv_calls_names %in% names(cnv_calls);
	
	# These Columns are generated by SMMCallCommand()
	smm_names = c("sample_id","Gender","SampleMeans","SampleMads","SampleMediansAuto","SampleMediansX");
	present2 = smm_names %in% names(sample_meansmads);
	
	if( (nrow(cnv_calls)>0 && length(unique(present)) == 1) && (unique(present)) ) {
		# All required columns are present
		# RULES:
		# Case 1: # >10Mb calls
		ccnx = cnv_calls[cnv_calls$chr=='X',]
		cl = ccnx$end-ccnx$start
		ccnx_Vlarge = ccnx[which(cl>10000000),] # >10Mb
		sids_lx = as.character(unique(ccnx_Vlarge$sample_id))  # all calls in this category
		#dx1 = dx[dx[,1] %in% sids_lx,]
		#rm1 = rownames(ccnx_Vlarge); ## remove_rows
		# Outlier samples in Step 1
		sids_o1 = sids_lx
		
		# Case 2: >1Mb calls + samples that are outliers in shift between mediansAuto vs mediansX (median log2 ratio of Auto vs X)
		# Case 2a: Determine OUTLIER samples
		
		if( (length(unique(present2)) == 1) && (unique(present2)) ) {
			dxx = sample_meansmads[abs(sample_meansmads$SampleMediansX) < abs_medianX_cutoff,]
			modlow <- lowess(dxx$SampleMediansX ~ dxx$SampleMediansAuto)
			modlow_resid <- (dxx$SampleMediansX)-modlow$y;
			SamplesAllResid <- data.frame(dxx,modlow_resid); names(SamplesAllResid)[ncol(SamplesAllResid)] = "LowessResidual";	
			SamplesAll2Return <- SamplesAllResid[abs(SamplesAllResid$LowessResidual)<(sd(modlow_resid)*sd_medians),];
			dxo = sample_meansmads[!(sample_meansmads[,1] %in% SamplesAll2Return$sample_id), ]
			outlier_samples = as.character(dxo$sample_id)
			
			# Case 2b: Row names of CNVs matching criteria
			ccnx_large = ccnx[which(cl>=500000 & cl<=10000000),];
			ccnx_large2 = ccnx_large[(ccnx_large$sample_id %in% outlier_samples),] # 
			rm2 = rownames(ccnx_large2); ## CNVs matching 2a and 2b
			# Outlier samples in Step 1 - Not all these are removed
			
			# Case 3: All calls in gender 'U' (unknown) samples - remove all ChrX calls 
			sids_o3 = as.character(sample_meansmads$sample_id[sample_meansmads$Gender=='U'])
			
			# Remove CNVs of samples matching Case 1 & Case3:
			samples2remove = unique(c(sids_o1,sids_o3))
			ccnx_retain1 = ccnx[!(ccnx$sample_id %in% samples2remove),];
			# Remove CNVs of samples matching Case 2:
			ccnx_retain2 = ccnx_retain1[!(rownames(ccnx_retain1) %in% rm2),]
			
			# Plot outliers
			if(nchar(outlier_plot_file)==0) {
				outlier_plot_file = paste("SampleMediansAuto_vs_MediansX_",nrow(sample_meansmads),"samples.png",sep="");
			}
			png(outlier_plot_file)
			plot(sample_meansmads$SampleMediansAuto,sample_meansmads$SampleMediansX, main="Median log2 ratio - Autosomes vs ChrX", xlab="Medians - Autosomes", ylab="Medians - Chr X", pch=19,cex=0.2,col=4);
			if(nrow(dxo)>0) {
				points(dxo$SampleMediansAuto,dxo$SampleMediansX,col=2,pch=3)
			}
			lines(modlow, col=2, lwd=2)
			mtext(paste(nrow(sample_meansmads)," samples"))
			dev.off()
			print(paste("Outlier plot file saved in the current directory:", outlier_plot_file))
			
			# Return ChrX samples			
			return(ccnx_retain2);
			
		} else {
			write("Missing the following column(s) (column names must match) in sample_meansmads:", stderr());
			write(smm_names[!present2], stderr());	
		}
	} else {
		write("CNV calls data frame with the following name(s) required (column names must match):", stderr());
		write(cnv_calls_names[!present], stderr());	
	}	
}

